# Generated by Django 6.0.6 on 2026-06-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariant_products_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size_name',
            field=models.ManyToManyField(blank=True, to='products.sizevariant'),
        ),
        migrations.AlterField(
            model_name='products',
            name='color_name',
            field=models.ManyToManyField(blank=True, to='products.colorvariant'),
        ),
    ]
